-- Câu 1
SELECT * FROM TACPHAM;
SELECT * FROM DOCGIA;
SELECT * FROM SACH;
SELECT * FROM MUON;

-- Câu 2


-- Câu 3
SELECT NT, TUA
FROM TACPHAM
WHERE TACGIA='Guy de Maupassant';

-- Câu 4
SELECT *
FROM DOCGIA
WHERE DCHI='32 rue des Alouettes, 75003 Paris';

-- Câu 5
SELECT s.NXB
FROM SACH s JOIN TACPHAM t ON s.NT = t.NT
WHERE t.TUA LIKE '%Fleur%';

-- Câu 6
SELECT TUA
FROM TACPHAM
WHERE TUA LIKE 'Le%';

-- Câu 7
SELECT d.TEN
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
WHERE m.NGAYMUON BETWEEN '2007-09-15' AND '2007-09-20';

-- Câu 8
SELECT DISTINCT s.NXB
FROM SACH s JOIN TACPHAM t ON s.NT = t.NT
WHERE t.TUA LIKE '%Germinal%';

-- Câu 9
SELECT DISTINCT d.TEN
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE t.TUA='Poésie';

-- Câu 10
SELECT DISTINCT d.*
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE t.TUA='Les Fleurs du mal';

-- Câu 11
SELECT t.TUA, d.TEN
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE m.NGAYTRA > m.HANTRA;

-- Câu 12
SELECT t.TUA, d.TEN
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE m.NGAYTRA < m.HANTRA;

-- Câu 13
SELECT DISTINCT d.TEN
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE t.TACGIA='Victor Hugo';

-- Câu 14
SELECT DISTINCT d.TEN, t.TUA
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE EXTRACT(YEAR FROM m.NGAYMUON)=2007
ORDER BY d.TEN;

-- Câu 15
SELECT COUNT(*) SOTACPHAM
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
              JOIN SACH s ON m.NS = s.NS
              JOIN TACPHAM t ON s.NT = t.NT
WHERE m.NGAYTRA < m.HANTRA;

-- Câu 16
SELECT DISTINCT t.TUA
FROM SACH s JOIN TACPHAM t ON s.NT = t.NT
GROUP BY t.TUA
HAVING COUNT(s.NT) >= 2
ORDER BY t.TUA;

-- Câu 17
SELECT t.TACGIA, COUNT(*) SOTACPHAM
FROM SACH s JOIN TACPHAM t ON s.NT = t.NT
GROUP BY t.TACGIA;

-- Câu 18
SELECT t.TUA, COUNT(*) SOTACPHAM
FROM SACH s JOIN TACPHAM t ON s.NT = t.NT
GROUP BY t.TUA;

-- Câu 19
SELECT d.TEN, COUNT(m.NGAYMUON) SOLANMUON
FROM DOCGIA d JOIN MUON m ON d.ND = m.ND
GROUP BY d.TEN;

-- Câu 20
SELECT t.TUA
FROM TACPHAM t JOIN SACH s ON t.NT = s.NT
GROUP BY t.TUA
HAVING COUNT(s.NS) >= 3;

-- Câu 21
CREATE TABLE CAU21 AS
SELECT t.TUA, COUNT(s.NS) SOSACH
FROM TACPHAM t JOIN SACH s ON t.NT = s.NT
GROUP BY t.TUA;

SELECT * FROM CAU21;

SELECT MAX(SOSACH)
FROM CAU21;

-- Câu 22
CREATE TABLE CAU22 AS
SELECT DISTINCT s.NXB, COUNT(s.NS) SOSACH
FROM SACH s JOIN TACPHAM t ON s.NT = t.NT
GROUP BY s.NXB;

SELECT NXB
FROM CAU22
WHERE SOSACH = (SELECT MAX(SOSACH) FROM CAU22);

-- Câu 23
SELECT COUNT(*) SOTACGIA
FROM (
    SELECT t.TACGIA, COUNT(*) SOTACPHAM
    FROM TACPHAM t JOIN SACH s ON t.NT = s.NT
    GROUP BY t.TACGIA
    HAVING COUNT(t.NT) >= 2
);

-- Câu 24


-- Câu 30
SELECT d.HO, d.TEN
FROM DOCGIA d LEFT JOIN MUON m ON d.ND = m.ND
WHERE m.NS IS NULL;

-- Câu 31
SELECT DISTINCT s.NXB
FROM SACH s LEFT JOIN MUON m ON s.NS = m.NS
WHERE m.NS IS NULL;