

-- 20
SELECT MAHV, MAX(DIEM) DIEMLONNHAT
FROM DIEM
GROUP BY MAHV;

-- 19
SELECT AVG(DIEM) DIEMTRUNGBINH
FROM HOCVIEN h JOIN DIEM d ON h.MAHV = d.MAHV
                JOIN LOP l ON d.MALOP = l.MALOP
                JOIN LOAILOP ll ON l.MALOAI = ll.MALOAI
WHERE h.TENHV='Ð¿ Gia B¿o' AND h.NGAYSINH='2001-12-02'
      AND l.TENLOP='L¿p 1' AND ll.TENLOAI='Ti¿ng Anh can b¿n';
      
-- 18
SELECT SUM(p.THANHTIEN) TONGSOTIEN
FROM PHIEUTHU p JOIN LOP l ON p.MALOP = l.MALOP
                JOIN KHOAHOC k ON l.MAKH = k.MAKH
WHERE k.TENKH='Khóa 1';

-- 17
SELECT SUM(p.THANHTIEN) TONGSOTIEN
FROM PHIEUTHU p JOIN LOP l ON p.MALOP = l.MALOP
                JOIN LOAILOP ll ON l.MALOAI = ll.MALOAI
WHERE l.TENLOP='L¿p 2' AND ll.TENLOAI='Ti¿ng Anh can b¿n';

-- 16
SELECT COUNT(*) SOHOCVIEN
FROM HOCVIEN h JOIN PHIEUTHU p ON h.MAHV = p.MAHV
                JOIN LOP l ON p.MALOP = l.MALOP
                JOIN LOAILOP ll ON l.MALOAI = ll.MALOAI
WHERE l.TENLOP='L¿p 1' AND ll.TENLOAI='Ti¿ng Anh can b¿n';

-- 15
SELECT COUNT(*) SOHOCVIEN
FROM HOCVIEN;

-- 14
SELECT h.TENHV, m.TENMH, d.DIEM
FROM HOCVIEN h JOIN DIEM d ON h.MAHV = d.MAHV
                JOIN MONHOC m ON d.MAMH = m.MAMH
                JOIN LOP l ON d.MALOP = l.MALOP
                JOIN KHOAHOC k ON l.MAKH = k.MAKH
WHERE k.TENKH='Khóa 1';

-- 13
SELECT p.*
FROM PHIEUTHU p JOIN LOP l ON p.MALOP = l.MALOP
                JOIN LOAILOP ll ON l.MALOAI = ll.MALOAI
WHERE ll.TENLOAI='Ti¿ng Anh A1' AND l.TENLOP='L¿p 1';

-- 12
SELECT l.*
FROM LOP l JOIN LOAILOP ll ON l.MALOAI = ll.MALOAI
            JOIN CHUONGTRINH ct ON ll.MACT = ct.MACT
WHERE ct.TENCT='Ti¿ng Anh T¿ng Quát';

-- 11
SELECT h.*
FROM HOCVIEN h JOIN PHIEUTHU p ON h.MAHV = p.MAHV
                JOIN LOP l ON p.MALOP = l.MALOP
                JOIN LOAILOP ll ON l.MALOAI = ll.MALOAI
WHERE ll.TENLOAI='Ti¿ng Anh can b¿n' AND l.TENLOP='L¿p 1';

-- 10
SELECT *
FROM PHIEUTHU
WHERE NGAYLAPPHIEU BETWEEN '2021-06-05' AND '2021-06-10';

-- 9
SELECT * 
FROM HOCVIEN
WHERE EXTRACT(YEAR from NGAYSINH) BETWEEN 1998 AND 2000;

-- 8
SELECT * 
FROM HOCVIEN
WHERE EXTRACT(YEAR from NGAYSINH)=2001 AND EXTRACT(MONTH from NGAYSINH)=12;

-- 7
SELECT * 
FROM HOCVIEN
WHERE EXTRACT(YEAR from NGAYSINH)=2000;

-- 6
SELECT TENHV
FROM HOCVIEN
WHERE TENHV LIKE 'Ð¿%';

-- 5
SELECT h.MAHV, h.TENHV
FROM HOCVIEN h JOIN PHIEUTHU p ON h.MAHV = p.MAHV
                JOIN LOP l ON p.MALOP = l.MALOP
                JOIN KHOAHOC k ON l.MAKH = k.MAKH
WHERE k.TENKH='Khóa 1';

-- 4
SELECT l.*
FROM LOP l JOIN KHOAHOC k ON l.MAKH = k.MAKH
WHERE k.TENKH='Khóa 1';

-- 3
SELECT *
FROM HOCVIEN
WHERE DIACHI LIKE '%C¿n Tho%'
ORDER BY MAHV;

-- 2
SELECT *
FROM HOCVIEN
WHERE GIOITINH=1
ORDER BY MAHV;

-- 1
SELECT * FROM KHOAHOC;
SELECT * FROM CHUONGTRINH;
SELECT * FROM LOAILOP;
SELECT * FROM LOP;
SELECT * FROM HOCVIEN;
SELECT * FROM PHIEUTHU;
SELECT * FROM MONHOC;
SELECT * FROM DIEM;
